name: Deploy Laravel App

on:
  push:
    branches:
      - ${{secrets.DEPLOY_BRANCH}}
  pull_request:
    branches:
      - ${{secrets.DEPLOY_BRANCH}}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh 
            cd ${{secrets.WORK_DIR}}
            echo "📦 Pulling latest code..."
            git fetch 
            git checkout ${{secrets.DEPLOY_BRANCH}}
            git pull 

            echo "🔧 Installing dependencies..."
            composer install --no-dev --optimize-autoloader

            echo "⚙️ Running Laravel optimizations..."
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "✅ Deployment complete."
            exit
